// Code generated by protoc-gen-go. DO NOT EDIT.
// source: icenter.proto

package proto

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type HardwareRequest struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HardwareRequest) Reset()         { *m = HardwareRequest{} }
func (m *HardwareRequest) String() string { return proto.CompactTextString(m) }
func (*HardwareRequest) ProtoMessage()    {}
func (*HardwareRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_5248017ed4825a92, []int{0}
}

func (m *HardwareRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HardwareRequest.Unmarshal(m, b)
}
func (m *HardwareRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HardwareRequest.Marshal(b, m, deterministic)
}
func (m *HardwareRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HardwareRequest.Merge(m, src)
}
func (m *HardwareRequest) XXX_Size() int {
	return xxx_messageInfo_HardwareRequest.Size(m)
}
func (m *HardwareRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_HardwareRequest.DiscardUnknown(m)
}

var xxx_messageInfo_HardwareRequest proto.InternalMessageInfo

func (m *HardwareRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type CPU struct {
	Core                 int32    `protobuf:"varint,2,opt,name=Core,proto3" json:"Core,omitempty"`
	Threads              int32    `protobuf:"varint,3,opt,name=Threads,proto3" json:"Threads,omitempty"`
	Cache                int64    `protobuf:"varint,4,opt,name=Cache,proto3" json:"Cache,omitempty"`
	Speed                int64    `protobuf:"varint,5,opt,name=Speed,proto3" json:"Speed,omitempty"`
	CPU                  int32    `protobuf:"varint,6,opt,name=CPU,proto3" json:"CPU,omitempty"`
	Model                string   `protobuf:"bytes,7,opt,name=Model,proto3" json:"Model,omitempty"`
	Vendor               string   `protobuf:"bytes,8,opt,name=Vendor,proto3" json:"Vendor,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CPU) Reset()         { *m = CPU{} }
func (m *CPU) String() string { return proto.CompactTextString(m) }
func (*CPU) ProtoMessage()    {}
func (*CPU) Descriptor() ([]byte, []int) {
	return fileDescriptor_5248017ed4825a92, []int{1}
}

func (m *CPU) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CPU.Unmarshal(m, b)
}
func (m *CPU) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CPU.Marshal(b, m, deterministic)
}
func (m *CPU) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CPU.Merge(m, src)
}
func (m *CPU) XXX_Size() int {
	return xxx_messageInfo_CPU.Size(m)
}
func (m *CPU) XXX_DiscardUnknown() {
	xxx_messageInfo_CPU.DiscardUnknown(m)
}

var xxx_messageInfo_CPU proto.InternalMessageInfo

func (m *CPU) GetCore() int32 {
	if m != nil {
		return m.Core
	}
	return 0
}

func (m *CPU) GetThreads() int32 {
	if m != nil {
		return m.Threads
	}
	return 0
}

func (m *CPU) GetCache() int64 {
	if m != nil {
		return m.Cache
	}
	return 0
}

func (m *CPU) GetSpeed() int64 {
	if m != nil {
		return m.Speed
	}
	return 0
}

func (m *CPU) GetCPU() int32 {
	if m != nil {
		return m.CPU
	}
	return 0
}

func (m *CPU) GetModel() string {
	if m != nil {
		return m.Model
	}
	return ""
}

func (m *CPU) GetVendor() string {
	if m != nil {
		return m.Vendor
	}
	return ""
}

type GPU struct {
	DriverVersion        string    `protobuf:"bytes,1,opt,name=DriverVersion,proto3" json:"DriverVersion,omitempty"`
	GPUs                 []*GPUXML `protobuf:"bytes,2,rep,name=GPUs,proto3" json:"GPUs,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *GPU) Reset()         { *m = GPU{} }
func (m *GPU) String() string { return proto.CompactTextString(m) }
func (*GPU) ProtoMessage()    {}
func (*GPU) Descriptor() ([]byte, []int) {
	return fileDescriptor_5248017ed4825a92, []int{2}
}

func (m *GPU) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GPU.Unmarshal(m, b)
}
func (m *GPU) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GPU.Marshal(b, m, deterministic)
}
func (m *GPU) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GPU.Merge(m, src)
}
func (m *GPU) XXX_Size() int {
	return xxx_messageInfo_GPU.Size(m)
}
func (m *GPU) XXX_DiscardUnknown() {
	xxx_messageInfo_GPU.DiscardUnknown(m)
}

var xxx_messageInfo_GPU proto.InternalMessageInfo

func (m *GPU) GetDriverVersion() string {
	if m != nil {
		return m.DriverVersion
	}
	return ""
}

func (m *GPU) GetGPUs() []*GPUXML {
	if m != nil {
		return m.GPUs
	}
	return nil
}

type Kernel struct {
	OSRelease            string   `protobuf:"bytes,1,opt,name=OSRelease,proto3" json:"OSRelease,omitempty"`
	OSType               string   `protobuf:"bytes,2,opt,name=OSType,proto3" json:"OSType,omitempty"`
	Version              string   `protobuf:"bytes,3,opt,name=Version,proto3" json:"Version,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Kernel) Reset()         { *m = Kernel{} }
func (m *Kernel) String() string { return proto.CompactTextString(m) }
func (*Kernel) ProtoMessage()    {}
func (*Kernel) Descriptor() ([]byte, []int) {
	return fileDescriptor_5248017ed4825a92, []int{3}
}

func (m *Kernel) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Kernel.Unmarshal(m, b)
}
func (m *Kernel) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Kernel.Marshal(b, m, deterministic)
}
func (m *Kernel) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Kernel.Merge(m, src)
}
func (m *Kernel) XXX_Size() int {
	return xxx_messageInfo_Kernel.Size(m)
}
func (m *Kernel) XXX_DiscardUnknown() {
	xxx_messageInfo_Kernel.DiscardUnknown(m)
}

var xxx_messageInfo_Kernel proto.InternalMessageInfo

func (m *Kernel) GetOSRelease() string {
	if m != nil {
		return m.OSRelease
	}
	return ""
}

func (m *Kernel) GetOSType() string {
	if m != nil {
		return m.OSType
	}
	return ""
}

func (m *Kernel) GetVersion() string {
	if m != nil {
		return m.Version
	}
	return ""
}

type Memory struct {
	MemTotal             int32    `protobuf:"varint,1,opt,name=MemTotal,proto3" json:"MemTotal,omitempty"`
	MemFree              int32    `protobuf:"varint,2,opt,name=MemFree,proto3" json:"MemFree,omitempty"`
	SwapTotal            int32    `protobuf:"varint,3,opt,name=SwapTotal,proto3" json:"SwapTotal,omitempty"`
	SwapFree             int32    `protobuf:"varint,4,opt,name=SwapFree,proto3" json:"SwapFree,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Memory) Reset()         { *m = Memory{} }
func (m *Memory) String() string { return proto.CompactTextString(m) }
func (*Memory) ProtoMessage()    {}
func (*Memory) Descriptor() ([]byte, []int) {
	return fileDescriptor_5248017ed4825a92, []int{4}
}

func (m *Memory) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Memory.Unmarshal(m, b)
}
func (m *Memory) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Memory.Marshal(b, m, deterministic)
}
func (m *Memory) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Memory.Merge(m, src)
}
func (m *Memory) XXX_Size() int {
	return xxx_messageInfo_Memory.Size(m)
}
func (m *Memory) XXX_DiscardUnknown() {
	xxx_messageInfo_Memory.DiscardUnknown(m)
}

var xxx_messageInfo_Memory proto.InternalMessageInfo

func (m *Memory) GetMemTotal() int32 {
	if m != nil {
		return m.MemTotal
	}
	return 0
}

func (m *Memory) GetMemFree() int32 {
	if m != nil {
		return m.MemFree
	}
	return 0
}

func (m *Memory) GetSwapTotal() int32 {
	if m != nil {
		return m.SwapTotal
	}
	return 0
}

func (m *Memory) GetSwapFree() int32 {
	if m != nil {
		return m.SwapFree
	}
	return 0
}

type Network struct {
	Name                 string   `protobuf:"bytes,1,opt,name=Name,proto3" json:"Name,omitempty"`
	IP                   string   `protobuf:"bytes,2,opt,name=IP,proto3" json:"IP,omitempty"`
	MACAddress           string   `protobuf:"bytes,3,opt,name=MACAddress,proto3" json:"MACAddress,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Network) Reset()         { *m = Network{} }
func (m *Network) String() string { return proto.CompactTextString(m) }
func (*Network) ProtoMessage()    {}
func (*Network) Descriptor() ([]byte, []int) {
	return fileDescriptor_5248017ed4825a92, []int{5}
}

func (m *Network) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Network.Unmarshal(m, b)
}
func (m *Network) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Network.Marshal(b, m, deterministic)
}
func (m *Network) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Network.Merge(m, src)
}
func (m *Network) XXX_Size() int {
	return xxx_messageInfo_Network.Size(m)
}
func (m *Network) XXX_DiscardUnknown() {
	xxx_messageInfo_Network.DiscardUnknown(m)
}

var xxx_messageInfo_Network proto.InternalMessageInfo

func (m *Network) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Network) GetIP() string {
	if m != nil {
		return m.IP
	}
	return ""
}

func (m *Network) GetMACAddress() string {
	if m != nil {
		return m.MACAddress
	}
	return ""
}

type OS struct {
	Name                 string   `protobuf:"bytes,1,opt,name=Name,proto3" json:"Name,omitempty"`
	Version              string   `protobuf:"bytes,2,opt,name=Version,proto3" json:"Version,omitempty"`
	CodeName             string   `protobuf:"bytes,3,opt,name=CodeName,proto3" json:"CodeName,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *OS) Reset()         { *m = OS{} }
func (m *OS) String() string { return proto.CompactTextString(m) }
func (*OS) ProtoMessage()    {}
func (*OS) Descriptor() ([]byte, []int) {
	return fileDescriptor_5248017ed4825a92, []int{6}
}

func (m *OS) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OS.Unmarshal(m, b)
}
func (m *OS) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OS.Marshal(b, m, deterministic)
}
func (m *OS) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OS.Merge(m, src)
}
func (m *OS) XXX_Size() int {
	return xxx_messageInfo_OS.Size(m)
}
func (m *OS) XXX_DiscardUnknown() {
	xxx_messageInfo_OS.DiscardUnknown(m)
}

var xxx_messageInfo_OS proto.InternalMessageInfo

func (m *OS) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *OS) GetVersion() string {
	if m != nil {
		return m.Version
	}
	return ""
}

func (m *OS) GetCodeName() string {
	if m != nil {
		return m.CodeName
	}
	return ""
}

type Storage struct {
	FileSystem           string   `protobuf:"bytes,1,opt,name=FileSystem,proto3" json:"FileSystem,omitempty"`
	Mount                string   `protobuf:"bytes,2,opt,name=Mount,proto3" json:"Mount,omitempty"`
	Total                int64    `protobuf:"varint,3,opt,name=Total,proto3" json:"Total,omitempty"`
	Used                 int64    `protobuf:"varint,4,opt,name=Used,proto3" json:"Used,omitempty"`
	Free                 int64    `protobuf:"varint,5,opt,name=Free,proto3" json:"Free,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Storage) Reset()         { *m = Storage{} }
func (m *Storage) String() string { return proto.CompactTextString(m) }
func (*Storage) ProtoMessage()    {}
func (*Storage) Descriptor() ([]byte, []int) {
	return fileDescriptor_5248017ed4825a92, []int{7}
}

func (m *Storage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Storage.Unmarshal(m, b)
}
func (m *Storage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Storage.Marshal(b, m, deterministic)
}
func (m *Storage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Storage.Merge(m, src)
}
func (m *Storage) XXX_Size() int {
	return xxx_messageInfo_Storage.Size(m)
}
func (m *Storage) XXX_DiscardUnknown() {
	xxx_messageInfo_Storage.DiscardUnknown(m)
}

var xxx_messageInfo_Storage proto.InternalMessageInfo

func (m *Storage) GetFileSystem() string {
	if m != nil {
		return m.FileSystem
	}
	return ""
}

func (m *Storage) GetMount() string {
	if m != nil {
		return m.Mount
	}
	return ""
}

func (m *Storage) GetTotal() int64 {
	if m != nil {
		return m.Total
	}
	return 0
}

func (m *Storage) GetUsed() int64 {
	if m != nil {
		return m.Used
	}
	return 0
}

func (m *Storage) GetFree() int64 {
	if m != nil {
		return m.Free
	}
	return 0
}

type StorageArray struct {
	Storages             []*Storage `protobuf:"bytes,1,rep,name=Storages,proto3" json:"Storages,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *StorageArray) Reset()         { *m = StorageArray{} }
func (m *StorageArray) String() string { return proto.CompactTextString(m) }
func (*StorageArray) ProtoMessage()    {}
func (*StorageArray) Descriptor() ([]byte, []int) {
	return fileDescriptor_5248017ed4825a92, []int{8}
}

func (m *StorageArray) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StorageArray.Unmarshal(m, b)
}
func (m *StorageArray) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StorageArray.Marshal(b, m, deterministic)
}
func (m *StorageArray) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StorageArray.Merge(m, src)
}
func (m *StorageArray) XXX_Size() int {
	return xxx_messageInfo_StorageArray.Size(m)
}
func (m *StorageArray) XXX_DiscardUnknown() {
	xxx_messageInfo_StorageArray.DiscardUnknown(m)
}

var xxx_messageInfo_StorageArray proto.InternalMessageInfo

func (m *StorageArray) GetStorages() []*Storage {
	if m != nil {
		return m.Storages
	}
	return nil
}

// GPUXML GPU info of a certain GPU
type GPUXML struct {
	ProductName          string           `protobuf:"bytes,1,opt,name=ProductName,proto3" json:"ProductName,omitempty"`
	FanSpeed             string           `protobuf:"bytes,2,opt,name=FanSpeed,proto3" json:"FanSpeed,omitempty"`
	FBMemory             *FBMemoryInfo    `protobuf:"bytes,3,opt,name=FBMemory,proto3" json:"FBMemory,omitempty"`
	Temperature          *TemperatureInfo `protobuf:"bytes,4,opt,name=Temperature,proto3" json:"Temperature,omitempty"`
	Clocks               *ClocksInfo      `protobuf:"bytes,5,opt,name=Clocks,proto3" json:"Clocks,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *GPUXML) Reset()         { *m = GPUXML{} }
func (m *GPUXML) String() string { return proto.CompactTextString(m) }
func (*GPUXML) ProtoMessage()    {}
func (*GPUXML) Descriptor() ([]byte, []int) {
	return fileDescriptor_5248017ed4825a92, []int{9}
}

func (m *GPUXML) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GPUXML.Unmarshal(m, b)
}
func (m *GPUXML) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GPUXML.Marshal(b, m, deterministic)
}
func (m *GPUXML) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GPUXML.Merge(m, src)
}
func (m *GPUXML) XXX_Size() int {
	return xxx_messageInfo_GPUXML.Size(m)
}
func (m *GPUXML) XXX_DiscardUnknown() {
	xxx_messageInfo_GPUXML.DiscardUnknown(m)
}

var xxx_messageInfo_GPUXML proto.InternalMessageInfo

func (m *GPUXML) GetProductName() string {
	if m != nil {
		return m.ProductName
	}
	return ""
}

func (m *GPUXML) GetFanSpeed() string {
	if m != nil {
		return m.FanSpeed
	}
	return ""
}

func (m *GPUXML) GetFBMemory() *FBMemoryInfo {
	if m != nil {
		return m.FBMemory
	}
	return nil
}

func (m *GPUXML) GetTemperature() *TemperatureInfo {
	if m != nil {
		return m.Temperature
	}
	return nil
}

func (m *GPUXML) GetClocks() *ClocksInfo {
	if m != nil {
		return m.Clocks
	}
	return nil
}

//ClocksInfo contains current frequency at which parts of the GPU are running.
type ClocksInfo struct {
	GraphicsClock        string   `protobuf:"bytes,1,opt,name=GraphicsClock,proto3" json:"GraphicsClock,omitempty"`
	SMClock              string   `protobuf:"bytes,2,opt,name=SMClock,proto3" json:"SMClock,omitempty"`
	MEMClock             string   `protobuf:"bytes,3,opt,name=MEMClock,proto3" json:"MEMClock,omitempty"`
	VideoClock           string   `protobuf:"bytes,4,opt,name=VideoClock,proto3" json:"VideoClock,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ClocksInfo) Reset()         { *m = ClocksInfo{} }
func (m *ClocksInfo) String() string { return proto.CompactTextString(m) }
func (*ClocksInfo) ProtoMessage()    {}
func (*ClocksInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_5248017ed4825a92, []int{10}
}

func (m *ClocksInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ClocksInfo.Unmarshal(m, b)
}
func (m *ClocksInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ClocksInfo.Marshal(b, m, deterministic)
}
func (m *ClocksInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ClocksInfo.Merge(m, src)
}
func (m *ClocksInfo) XXX_Size() int {
	return xxx_messageInfo_ClocksInfo.Size(m)
}
func (m *ClocksInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_ClocksInfo.DiscardUnknown(m)
}

var xxx_messageInfo_ClocksInfo proto.InternalMessageInfo

func (m *ClocksInfo) GetGraphicsClock() string {
	if m != nil {
		return m.GraphicsClock
	}
	return ""
}

func (m *ClocksInfo) GetSMClock() string {
	if m != nil {
		return m.SMClock
	}
	return ""
}

func (m *ClocksInfo) GetMEMClock() string {
	if m != nil {
		return m.MEMClock
	}
	return ""
}

func (m *ClocksInfo) GetVideoClock() string {
	if m != nil {
		return m.VideoClock
	}
	return ""
}

// FBMemoryInfo contains on-board frame buffer memory information.
type FBMemoryInfo struct {
	Total                string   `protobuf:"bytes,1,opt,name=Total,proto3" json:"Total,omitempty"`
	Used                 string   `protobuf:"bytes,2,opt,name=Used,proto3" json:"Used,omitempty"`
	Free                 string   `protobuf:"bytes,3,opt,name=Free,proto3" json:"Free,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FBMemoryInfo) Reset()         { *m = FBMemoryInfo{} }
func (m *FBMemoryInfo) String() string { return proto.CompactTextString(m) }
func (*FBMemoryInfo) ProtoMessage()    {}
func (*FBMemoryInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_5248017ed4825a92, []int{11}
}

func (m *FBMemoryInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FBMemoryInfo.Unmarshal(m, b)
}
func (m *FBMemoryInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FBMemoryInfo.Marshal(b, m, deterministic)
}
func (m *FBMemoryInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FBMemoryInfo.Merge(m, src)
}
func (m *FBMemoryInfo) XXX_Size() int {
	return xxx_messageInfo_FBMemoryInfo.Size(m)
}
func (m *FBMemoryInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_FBMemoryInfo.DiscardUnknown(m)
}

var xxx_messageInfo_FBMemoryInfo proto.InternalMessageInfo

func (m *FBMemoryInfo) GetTotal() string {
	if m != nil {
		return m.Total
	}
	return ""
}

func (m *FBMemoryInfo) GetUsed() string {
	if m != nil {
		return m.Used
	}
	return ""
}

func (m *FBMemoryInfo) GetFree() string {
	if m != nil {
		return m.Free
	}
	return ""
}

//TemperatureInfo contains readings from temperature sensors on the board.
type TemperatureInfo struct {
	GPUTemperature       string   `protobuf:"bytes,1,opt,name=GPUTemperature,proto3" json:"GPUTemperature,omitempty"`
	MemoryTemperature    string   `protobuf:"bytes,2,opt,name=MemoryTemperature,proto3" json:"MemoryTemperature,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TemperatureInfo) Reset()         { *m = TemperatureInfo{} }
func (m *TemperatureInfo) String() string { return proto.CompactTextString(m) }
func (*TemperatureInfo) ProtoMessage()    {}
func (*TemperatureInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_5248017ed4825a92, []int{12}
}

func (m *TemperatureInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TemperatureInfo.Unmarshal(m, b)
}
func (m *TemperatureInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TemperatureInfo.Marshal(b, m, deterministic)
}
func (m *TemperatureInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TemperatureInfo.Merge(m, src)
}
func (m *TemperatureInfo) XXX_Size() int {
	return xxx_messageInfo_TemperatureInfo.Size(m)
}
func (m *TemperatureInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_TemperatureInfo.DiscardUnknown(m)
}

var xxx_messageInfo_TemperatureInfo proto.InternalMessageInfo

func (m *TemperatureInfo) GetGPUTemperature() string {
	if m != nil {
		return m.GPUTemperature
	}
	return ""
}

func (m *TemperatureInfo) GetMemoryTemperature() string {
	if m != nil {
		return m.MemoryTemperature
	}
	return ""
}

type HardwareResponse struct {
	// string message = 1;
	OSInfo               *OS                      `protobuf:"bytes,1,opt,name=OSInfo,proto3" json:"OSInfo,omitempty"`
	CPUInfo              *CPU                     `protobuf:"bytes,2,opt,name=CPUInfo,proto3" json:"CPUInfo,omitempty"`
	GPUInfos             *GPU                     `protobuf:"bytes,3,opt,name=GPUInfos,proto3" json:"GPUInfos,omitempty"`
	KernelInfo           *Kernel                  `protobuf:"bytes,4,opt,name=KernelInfo,proto3" json:"KernelInfo,omitempty"`
	MemoryInfo           *Memory                  `protobuf:"bytes,5,opt,name=MemoryInfo,proto3" json:"MemoryInfo,omitempty"`
	NetworkInfos         []*Network               `protobuf:"bytes,6,rep,name=NetworkInfos,proto3" json:"NetworkInfos,omitempty"`
	StorageInfo          map[string]*StorageArray `protobuf:"bytes,7,rep,name=StorageInfo,proto3" json:"StorageInfo,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}                 `json:"-"`
	XXX_unrecognized     []byte                   `json:"-"`
	XXX_sizecache        int32                    `json:"-"`
}

func (m *HardwareResponse) Reset()         { *m = HardwareResponse{} }
func (m *HardwareResponse) String() string { return proto.CompactTextString(m) }
func (*HardwareResponse) ProtoMessage()    {}
func (*HardwareResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_5248017ed4825a92, []int{13}
}

func (m *HardwareResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HardwareResponse.Unmarshal(m, b)
}
func (m *HardwareResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HardwareResponse.Marshal(b, m, deterministic)
}
func (m *HardwareResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HardwareResponse.Merge(m, src)
}
func (m *HardwareResponse) XXX_Size() int {
	return xxx_messageInfo_HardwareResponse.Size(m)
}
func (m *HardwareResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_HardwareResponse.DiscardUnknown(m)
}

var xxx_messageInfo_HardwareResponse proto.InternalMessageInfo

func (m *HardwareResponse) GetOSInfo() *OS {
	if m != nil {
		return m.OSInfo
	}
	return nil
}

func (m *HardwareResponse) GetCPUInfo() *CPU {
	if m != nil {
		return m.CPUInfo
	}
	return nil
}

func (m *HardwareResponse) GetGPUInfos() *GPU {
	if m != nil {
		return m.GPUInfos
	}
	return nil
}

func (m *HardwareResponse) GetKernelInfo() *Kernel {
	if m != nil {
		return m.KernelInfo
	}
	return nil
}

func (m *HardwareResponse) GetMemoryInfo() *Memory {
	if m != nil {
		return m.MemoryInfo
	}
	return nil
}

func (m *HardwareResponse) GetNetworkInfos() []*Network {
	if m != nil {
		return m.NetworkInfos
	}
	return nil
}

func (m *HardwareResponse) GetStorageInfo() map[string]*StorageArray {
	if m != nil {
		return m.StorageInfo
	}
	return nil
}

// The request message
type UpperRequest struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpperRequest) Reset()         { *m = UpperRequest{} }
func (m *UpperRequest) String() string { return proto.CompactTextString(m) }
func (*UpperRequest) ProtoMessage()    {}
func (*UpperRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_5248017ed4825a92, []int{14}
}

func (m *UpperRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpperRequest.Unmarshal(m, b)
}
func (m *UpperRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpperRequest.Marshal(b, m, deterministic)
}
func (m *UpperRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpperRequest.Merge(m, src)
}
func (m *UpperRequest) XXX_Size() int {
	return xxx_messageInfo_UpperRequest.Size(m)
}
func (m *UpperRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpperRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpperRequest proto.InternalMessageInfo

func (m *UpperRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

// The response message
type UpperReply struct {
	Message              string   `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpperReply) Reset()         { *m = UpperReply{} }
func (m *UpperReply) String() string { return proto.CompactTextString(m) }
func (*UpperReply) ProtoMessage()    {}
func (*UpperReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_5248017ed4825a92, []int{15}
}

func (m *UpperReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpperReply.Unmarshal(m, b)
}
func (m *UpperReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpperReply.Marshal(b, m, deterministic)
}
func (m *UpperReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpperReply.Merge(m, src)
}
func (m *UpperReply) XXX_Size() int {
	return xxx_messageInfo_UpperReply.Size(m)
}
func (m *UpperReply) XXX_DiscardUnknown() {
	xxx_messageInfo_UpperReply.DiscardUnknown(m)
}

var xxx_messageInfo_UpperReply proto.InternalMessageInfo

func (m *UpperReply) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func init() {
	proto.RegisterType((*HardwareRequest)(nil), "proto.HardwareRequest")
	proto.RegisterType((*CPU)(nil), "proto.CPU")
	proto.RegisterType((*GPU)(nil), "proto.GPU")
	proto.RegisterType((*Kernel)(nil), "proto.Kernel")
	proto.RegisterType((*Memory)(nil), "proto.Memory")
	proto.RegisterType((*Network)(nil), "proto.Network")
	proto.RegisterType((*OS)(nil), "proto.OS")
	proto.RegisterType((*Storage)(nil), "proto.Storage")
	proto.RegisterType((*StorageArray)(nil), "proto.StorageArray")
	proto.RegisterType((*GPUXML)(nil), "proto.GPUXML")
	proto.RegisterType((*ClocksInfo)(nil), "proto.ClocksInfo")
	proto.RegisterType((*FBMemoryInfo)(nil), "proto.FBMemoryInfo")
	proto.RegisterType((*TemperatureInfo)(nil), "proto.TemperatureInfo")
	proto.RegisterType((*HardwareResponse)(nil), "proto.HardwareResponse")
	proto.RegisterMapType((map[string]*StorageArray)(nil), "proto.HardwareResponse.StorageInfoEntry")
	proto.RegisterType((*UpperRequest)(nil), "proto.UpperRequest")
	proto.RegisterType((*UpperReply)(nil), "proto.UpperReply")
}

func init() { proto.RegisterFile("icenter.proto", fileDescriptor_5248017ed4825a92) }

var fileDescriptor_5248017ed4825a92 = []byte{
	// 918 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x56, 0xcd, 0x6e, 0xdb, 0x46,
	0x10, 0x8e, 0xfe, 0xe5, 0x91, 0xe2, 0x9f, 0x4d, 0xe0, 0x12, 0x46, 0x51, 0x28, 0x44, 0x6a, 0x28,
	0x45, 0xeb, 0xa2, 0xea, 0x25, 0x08, 0x7a, 0x71, 0x94, 0x58, 0x75, 0x1b, 0xd9, 0xc4, 0x52, 0x32,
	0x82, 0xde, 0x58, 0x71, 0x6a, 0x0b, 0xa6, 0x48, 0x76, 0x49, 0xc5, 0xd5, 0xa1, 0xf7, 0xbe, 0x45,
	0xdf, 0xa2, 0x4f, 0xd3, 0x87, 0x29, 0x76, 0x66, 0x57, 0x24, 0x95, 0xb6, 0x27, 0xed, 0xf7, 0xcd,
	0xec, 0xcc, 0xec, 0x37, 0xb3, 0x4b, 0xc1, 0xe3, 0xe5, 0x02, 0xe3, 0x1c, 0xd5, 0x59, 0xaa, 0x92,
	0x3c, 0x11, 0x2d, 0xfa, 0x71, 0x3f, 0x87, 0x83, 0xef, 0x03, 0x15, 0x3e, 0x04, 0x0a, 0x25, 0xfe,
	0xba, 0xc6, 0x2c, 0x17, 0x02, 0x9a, 0x71, 0xb0, 0x42, 0xa7, 0x36, 0xa8, 0x0d, 0xf7, 0x24, 0xad,
	0xdd, 0x3f, 0x6b, 0xd0, 0x18, 0x7b, 0x73, 0x6d, 0x1b, 0x27, 0x0a, 0x9d, 0xfa, 0xa0, 0x36, 0x6c,
	0x49, 0x5a, 0x0b, 0x07, 0x3a, 0xb3, 0x3b, 0x85, 0x41, 0x98, 0x39, 0x0d, 0xa2, 0x2d, 0x14, 0x4f,
	0xa1, 0x35, 0x0e, 0x16, 0x77, 0xe8, 0x34, 0x07, 0xb5, 0x61, 0x43, 0x32, 0xd0, 0xac, 0x9f, 0x22,
	0x86, 0x4e, 0x8b, 0x59, 0x02, 0xe2, 0x90, 0x12, 0x38, 0x6d, 0x8a, 0x40, 0xb9, 0x9e, 0x42, 0x6b,
	0x9a, 0x84, 0x18, 0x39, 0x1d, 0x2a, 0x84, 0x81, 0x38, 0x86, 0xf6, 0x0d, 0xc6, 0x61, 0xa2, 0x9c,
	0x2e, 0xd1, 0x06, 0xb9, 0x57, 0xd0, 0x98, 0x78, 0x73, 0xf1, 0x1c, 0x1e, 0xbf, 0x51, 0xcb, 0x0f,
	0xa8, 0x6e, 0x50, 0x65, 0xcb, 0x24, 0x36, 0xa7, 0xa8, 0x92, 0xe2, 0x19, 0x34, 0x27, 0xde, 0x3c,
	0x73, 0xea, 0x83, 0xc6, 0xb0, 0x37, 0x7a, 0xcc, 0x92, 0x9c, 0x4d, 0xbc, 0xf9, 0xfb, 0xe9, 0x3b,
	0x49, 0x26, 0xf7, 0x3d, 0xb4, 0x7f, 0x44, 0x15, 0x63, 0x24, 0x3e, 0x85, 0xbd, 0x6b, 0x5f, 0x62,
	0x84, 0x41, 0x66, 0x45, 0x29, 0x08, 0x5d, 0xcf, 0xb5, 0x3f, 0xdb, 0xa4, 0xac, 0xc9, 0x9e, 0x34,
	0x48, 0xab, 0x62, 0x4b, 0x68, 0x90, 0xc1, 0x42, 0xf7, 0x37, 0x68, 0x4f, 0x71, 0x95, 0xa8, 0x8d,
	0x38, 0x81, 0xee, 0x14, 0x57, 0xb3, 0x24, 0x0f, 0x22, 0x0a, 0xdc, 0x92, 0x5b, 0xac, 0xf7, 0x4f,
	0x71, 0x75, 0xa1, 0xd0, 0x8a, 0x6d, 0xa1, 0xae, 0xc7, 0x7f, 0x08, 0x52, 0xde, 0xc6, 0x8a, 0x17,
	0x84, 0x8e, 0xa9, 0x01, 0x6d, 0x6c, 0x72, 0x4c, 0x8b, 0xdd, 0x29, 0x74, 0xae, 0x30, 0x7f, 0x48,
	0xd4, 0xbd, 0x6e, 0xe4, 0x55, 0xa9, 0xc9, 0x7a, 0x2d, 0xf6, 0xa1, 0x7e, 0xe9, 0x99, 0x63, 0xd4,
	0x2f, 0x3d, 0xf1, 0x19, 0xc0, 0xf4, 0x7c, 0x7c, 0x1e, 0x86, 0x0a, 0xb3, 0xcc, 0x9c, 0xa2, 0xc4,
	0xb8, 0x57, 0x50, 0xbf, 0xf6, 0xff, 0x35, 0x52, 0xe9, 0xf0, 0xf5, 0xca, 0xe1, 0x75, 0x79, 0xe3,
	0x24, 0x44, 0xda, 0xc1, 0x11, 0xb7, 0xd8, 0xfd, 0x1d, 0x3a, 0x7e, 0x9e, 0xa8, 0xe0, 0x16, 0x75,
	0xea, 0x8b, 0x65, 0x84, 0xfe, 0x26, 0xcb, 0x71, 0x65, 0x42, 0x97, 0x18, 0x9e, 0x8d, 0x75, 0x9c,
	0x9b, 0xf0, 0x0c, 0x34, 0x5b, 0xa8, 0xd2, 0x90, 0x0c, 0x74, 0x81, 0xf3, 0x0c, 0x43, 0x33, 0x84,
	0xb4, 0xd6, 0x1c, 0x29, 0xc4, 0x23, 0x48, 0x6b, 0xf7, 0x15, 0xf4, 0x4d, 0xfa, 0x73, 0xa5, 0x82,
	0x8d, 0xf8, 0x02, 0xba, 0x06, 0x67, 0x4e, 0x8d, 0x06, 0x65, 0xdf, 0x0c, 0x8a, 0xa1, 0xe5, 0xd6,
	0xee, 0xfe, 0x5d, 0x83, 0x36, 0x8f, 0x8f, 0x18, 0x40, 0xcf, 0x53, 0x49, 0xb8, 0x5e, 0xe4, 0x25,
	0x59, 0xca, 0x94, 0xd6, 0xe0, 0x22, 0x88, 0xf9, 0x0e, 0x70, 0xfd, 0x5b, 0x2c, 0xbe, 0x86, 0xee,
	0xc5, 0x6b, 0x1e, 0x0f, 0x3a, 0x45, 0x6f, 0xf4, 0xc4, 0x24, 0xb5, 0xf4, 0x65, 0xfc, 0x4b, 0x22,
	0xb7, 0x4e, 0xe2, 0x25, 0xf4, 0x66, 0xb8, 0x4a, 0x51, 0x05, 0xf9, 0x5a, 0x71, 0xcb, 0x7b, 0xa3,
	0x63, 0xb3, 0xa7, 0x64, 0xa1, 0x6d, 0x65, 0x57, 0xf1, 0x02, 0xda, 0xe3, 0x28, 0x59, 0xdc, 0x67,
	0xa4, 0x42, 0x6f, 0x74, 0x64, 0x36, 0x31, 0x49, 0xfe, 0xc6, 0xc1, 0xfd, 0xa3, 0x06, 0x50, 0xd0,
	0xfa, 0x92, 0x4d, 0x54, 0x90, 0xde, 0x2d, 0x17, 0x19, 0xb1, 0xf6, 0x92, 0x55, 0x48, 0x3d, 0x04,
	0xfe, 0x94, 0xed, 0x66, 0x08, 0x0c, 0xa4, 0xb9, 0x7f, 0x6b, 0x4c, 0x66, 0x08, 0x2c, 0xd6, 0x9d,
	0xbf, 0x59, 0x86, 0x98, 0xb0, 0xb5, 0xc9, 0x9d, 0x2f, 0x18, 0xf7, 0x1d, 0xf4, 0xcb, 0x4a, 0x14,
	0x3d, 0xe7, 0x1a, 0x76, 0x7a, 0xce, 0x89, 0xab, 0x3d, 0xe7, 0x8c, 0xdc, 0xf3, 0x5b, 0x38, 0xd8,
	0xd1, 0x48, 0x9c, 0xc2, 0xfe, 0xc4, 0x9b, 0x97, 0x35, 0xe5, 0xc8, 0x3b, 0xac, 0xf8, 0x12, 0x8e,
	0xb8, 0x8c, 0xb2, 0x2b, 0xe7, 0xfb, 0xd8, 0xe0, 0xfe, 0xd5, 0x80, 0xc3, 0xe2, 0xa1, 0xcd, 0xd2,
	0x24, 0xce, 0x50, 0x3c, 0xd3, 0x6f, 0x87, 0x4e, 0x4a, 0x29, 0x7a, 0xa3, 0x3d, 0xd3, 0x81, 0x6b,
	0x5f, 0x1a, 0x83, 0x78, 0x0e, 0x9d, 0xb1, 0x37, 0x27, 0x9f, 0x3a, 0xf9, 0x80, 0xed, 0x92, 0x37,
	0x97, 0xd6, 0x24, 0x4e, 0xa1, 0x3b, 0xe1, 0x65, 0x66, 0xa6, 0x06, 0x8a, 0x37, 0x4d, 0x6e, 0x6d,
	0xe2, 0x2b, 0x00, 0x7e, 0xd4, 0x28, 0x20, 0xcf, 0x8a, 0x7d, 0xfd, 0xd8, 0x20, 0x4b, 0x0e, 0xda,
	0xbd, 0x50, 0xda, 0x4c, 0x89, 0x75, 0x67, 0x83, 0x2c, 0x39, 0x88, 0x11, 0xf4, 0xcd, 0xf3, 0xc2,
	0x95, 0xb4, 0x2b, 0x97, 0xc6, 0x98, 0x64, 0xc5, 0x47, 0xfc, 0x00, 0x3d, 0x73, 0x89, 0x28, 0x47,
	0x87, 0xb6, 0x0c, 0xcd, 0x96, 0x5d, 0xc1, 0xce, 0x4a, 0xae, 0x6f, 0xe3, 0x5c, 0x6d, 0x64, 0x79,
	0xf3, 0x89, 0x0f, 0x87, 0xbb, 0x0e, 0xfa, 0xb3, 0x72, 0x8f, 0x1b, 0xd3, 0x42, 0xbd, 0x14, 0x2f,
	0xa0, 0xf5, 0x21, 0x88, 0xd6, 0x68, 0xf4, 0x7c, 0x52, 0xbd, 0xd3, 0x74, 0xf5, 0x25, 0x7b, 0xbc,
	0xaa, 0xbf, 0xac, 0xb9, 0x2e, 0xf4, 0xe7, 0x69, 0x8a, 0xea, 0xff, 0xbe, 0x8e, 0xa7, 0x00, 0xc6,
	0x27, 0x8d, 0x36, 0x7a, 0xee, 0x57, 0x98, 0x65, 0xc1, 0xad, 0x75, 0xb2, 0x70, 0x34, 0x83, 0xbe,
	0x3d, 0x12, 0x09, 0xf6, 0x06, 0x0e, 0x26, 0x98, 0x57, 0xa8, 0xe3, 0x8f, 0x8e, 0x4e, 0x69, 0x4f,
	0x3e, 0xf9, 0x0f, 0x49, 0xdc, 0x47, 0xa3, 0xef, 0xa0, 0x33, 0x4b, 0x28, 0xbf, 0xf8, 0x06, 0x5a,
	0xbc, 0xb0, 0xa7, 0x2a, 0x97, 0x7e, 0x72, 0x54, 0x25, 0xd3, 0x68, 0xe3, 0x3e, 0x7a, 0xdd, 0xf9,
	0x89, 0xff, 0x09, 0xfc, 0xdc, 0xa6, 0x9f, 0x6f, 0xff, 0x09, 0x00, 0x00, 0xff, 0xff, 0xfe, 0x0c,
	0x82, 0x5f, 0x28, 0x08, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// HardwareInfoClient is the client API for HardwareInfo service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type HardwareInfoClient interface {
	GetHardwareInfo(ctx context.Context, in *HardwareRequest, opts ...grpc.CallOption) (*HardwareResponse, error)
}

type hardwareInfoClient struct {
	cc *grpc.ClientConn
}

func NewHardwareInfoClient(cc *grpc.ClientConn) HardwareInfoClient {
	return &hardwareInfoClient{cc}
}

func (c *hardwareInfoClient) GetHardwareInfo(ctx context.Context, in *HardwareRequest, opts ...grpc.CallOption) (*HardwareResponse, error) {
	out := new(HardwareResponse)
	err := c.cc.Invoke(ctx, "/proto.HardwareInfo/GetHardwareInfo", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// HardwareInfoServer is the server API for HardwareInfo service.
type HardwareInfoServer interface {
	GetHardwareInfo(context.Context, *HardwareRequest) (*HardwareResponse, error)
}

// UnimplementedHardwareInfoServer can be embedded to have forward compatible implementations.
type UnimplementedHardwareInfoServer struct {
}

func (*UnimplementedHardwareInfoServer) GetHardwareInfo(ctx context.Context, req *HardwareRequest) (*HardwareResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetHardwareInfo not implemented")
}

func RegisterHardwareInfoServer(s *grpc.Server, srv HardwareInfoServer) {
	s.RegisterService(&_HardwareInfo_serviceDesc, srv)
}

func _HardwareInfo_GetHardwareInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HardwareRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HardwareInfoServer).GetHardwareInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.HardwareInfo/GetHardwareInfo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HardwareInfoServer).GetHardwareInfo(ctx, req.(*HardwareRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _HardwareInfo_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.HardwareInfo",
	HandlerType: (*HardwareInfoServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetHardwareInfo",
			Handler:    _HardwareInfo_GetHardwareInfo_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "icenter.proto",
}

// ToUpperClient is the client API for ToUpper service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ToUpperClient interface {
	// Sends a greeting
	Upper(ctx context.Context, in *UpperRequest, opts ...grpc.CallOption) (*UpperReply, error)
}

type toUpperClient struct {
	cc *grpc.ClientConn
}

func NewToUpperClient(cc *grpc.ClientConn) ToUpperClient {
	return &toUpperClient{cc}
}

func (c *toUpperClient) Upper(ctx context.Context, in *UpperRequest, opts ...grpc.CallOption) (*UpperReply, error) {
	out := new(UpperReply)
	err := c.cc.Invoke(ctx, "/proto.ToUpper/Upper", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ToUpperServer is the server API for ToUpper service.
type ToUpperServer interface {
	// Sends a greeting
	Upper(context.Context, *UpperRequest) (*UpperReply, error)
}

// UnimplementedToUpperServer can be embedded to have forward compatible implementations.
type UnimplementedToUpperServer struct {
}

func (*UnimplementedToUpperServer) Upper(ctx context.Context, req *UpperRequest) (*UpperReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Upper not implemented")
}

func RegisterToUpperServer(s *grpc.Server, srv ToUpperServer) {
	s.RegisterService(&_ToUpper_serviceDesc, srv)
}

func _ToUpper_Upper_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpperRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ToUpperServer).Upper(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.ToUpper/Upper",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ToUpperServer).Upper(ctx, req.(*UpperRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _ToUpper_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.ToUpper",
	HandlerType: (*ToUpperServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Upper",
			Handler:    _ToUpper_Upper_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "icenter.proto",
}
